version: "3.8"
services:
  config-server:
    container_name: config-server
    image: cfretamales/config-server:latest
    ports:
      - "8081:8081"
  eureka-service:
    container_name: eureka
    image: cfretamales/eureka:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    links:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - spring.config.import=optional:configserver:http://config-server:8081