version: "3.8"
services:
  config-server:
    container_name: config-server
    image: cfretamales/config-server:latest
    ports:
      - "8081:8081"
  eureka:
    container_name: eureka
    image: cfretamales/eureka:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    links:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - spring.config.import=optional:configserver:http://config-server:8081
  api-gateway:
    container_name: api-gateway
    image: cfretamales/api-gateway:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - spring.config.import=optional:configserver:http://config-server:8081
      - EUREKA_URL=http://eureka:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka
    links:
      - config-server
      - eureka
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=7214
        - POSTGRES_DB=msdb
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    deploy:
        restart_policy:
            condition: on-failure
  employee:
    container_name: employee
    image: cfretamales/employee:latest
    ports:
      - "8091:8091"
    environment:
        - spring.config.import=optional:configserver:http://config-server:8081
        - EUREKA_URL=http://eureka:8761/eureka/
        - DB_URL=jdbc:postgresql://postgres-db:5432/msdb
        - DB_USERNAME=postgres
        - DB_PASSWORD=7214
    depends_on:
        - config-server
        - eureka
        - postgres-db
    links:
        - config-server
        - eureka
        - postgres-db
    deploy:
        restart_policy:
            condition: on-failure
  hour:
    container_name: hour
    image: cfretamales/hour:latest
    ports:
      - "8092:8092"
    environment:
        - spring.config.import=optional:configserver:http://config-server:8081
        - EUREKA_URL=http://eureka:8761/eureka/
        - DB_URL=jdbc:postgresql://postgres-db:5432/msdb
        - DB_USERNAME=postgres
        - DB_PASSWORD=7214
    depends_on:
        - config-server
        - eureka
        - postgres-db
    links:
        - config-server
        - eureka
        - postgres-db
    deploy:
        restart_policy:
            condition: on-failure
  justification:
    container_name: justification
    image: cfretamales/justification:latest
    ports:
      - "8093:8093"
    environment:
        - spring.config.import=optional:configserver:http://config-server:8081
        - EUREKA_URL=http://eureka:8761/eureka/
        - DB_URL=jdbc:postgresql://postgres-db:5432/msdb
        - DB_USERNAME=postgres
        - DB_PASSWORD=7214
    depends_on:
        - config-server
        - eureka
        - postgres-db
    links:
        - config-server
        - eureka
        - postgres-db
    deploy:
        restart_policy:
            condition: on-failure
  mark:
    container_name: mark
    image: cfretamales/mark:latest
    ports:
      - "8094:8094"
    environment:
        - spring.config.import=optional:configserver:http://config-server:8081
        - EUREKA_URL=http://eureka:8761/eureka/
        - DB_URL=jdbc:postgresql://postgres-db:5432/msdb
        - DB_USERNAME=postgres
        - DB_PASSWORD=7214
    depends_on:
        - config-server
        - eureka
        - postgres-db
    links:
        - config-server
        - eureka
        - postgres-db
    deploy:
        restart_policy:
            condition: on-failure
  report:
    container_name: report
    image: cfretamales/report:latest
    ports:
      - "8095:8095"
    environment:
        - spring.config.import=optional:configserver:http://config-server:8081
        - EUREKA_URL=http://eureka:8761/eureka/
        - DB_URL=jdbc:postgresql://postgres-db:5432/msdb
        - DB_USERNAME=postgres
        - DB_PASSWORD=7214
    depends_on:
        - config-server
        - eureka
        - postgres-db
    links:
        - config-server
        - eureka
        - postgres-db
    deploy:
        restart_policy:
            condition: on-failure
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - report
      - api-gateway
    links:
      - report
      - api-gateway
    deploy:
      restart_policy:
        condition: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    links:
      - prometheus
    deploy:
      restart_policy:
        condition: on-failure
  react:
    container_name: react
    image: cfretamales/react:latest
    ports:
      - "3000:3000"
    depends_on:
        - api-gateway
    links:
        - api-gateway
    deploy:
        restart_policy:
            condition: on-failure



