scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'report'
        type: 'A' 
        port: 8095
