server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/employee/**
        - id: hour
          uri: lb://hour
          predicates:
            - Path=/hour/**
        - id: justification
          uri: lb://justification
          predicates:
            - Path=/justification/**
        - id: mark
          uri: lb://mark
          predicates:
            - Path=/mark/**
        - id: report
          uri: lb://report
          predicates:
            - Path=/report/**

      #CORRECCION DE ERROR DE CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
