spring:
  application:
    name: eureka
  cloud:
    config:
      retry:
        maxAttempts: 200
        maxInterval: 10000

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


