#Configuracion de propiedades
server:
  port: 8096
  error:
    include-message: always

spring:
  # Base de Datos
  postgresql:
    console:
      enabled:true
  dataSource:
    #Configuracion de la base de datos
    #postgresql
    driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/msdb
    #username: postgres
    #password: 7214
    url: ${DB_URL:jdbc:postgresql://localhost:5432/msdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:7214}



  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}