server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CRetamales/MueblesStgo
          search-paths: config-data
          default-label: develop #Despues cambiar a master
  application:
    name: config-service
